default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: refileapp
  pool: 5
  username: user1
  password: user1
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: refileapp
  pool: 5
  username: user1
  password: user1
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: refileapp
  pool: 5
  username: user1
  password: user1
  host: localhost
